apiVersion: v1
kind: PersistentVolume
metadata:
# 아래 name 은 어떤 이름이라도 상관 없음 
  name: nfs-pv
  labels:
    volume: nfs-pv-volume 
spec:
  capacity:
# 스토리지 크기 결정 
    storage: 50Gi
  accessModes:
    # ReadWriteMany - multi node 에서 읽고 쓰기가 가능
    - ReadWriteMany 
  persistentVolumeReclaimPolicy:
  # retain even if pods terminate 
    Retain
  nfs:
    # NFS server's definition
    # nfs 공유 디렉토리 
    path: /nfs
    # nfs 서버의 주소  
    server: 10.178.0.16
    # 공유디렉토리에 대해서 읽고 쓰기 권한 부여 
    readOnly: false
